name = "App-Greple-xlate"
badges = [ "github-actions/test.yml" ]
script_files = [ "script/xlate" ]
authority = "cpan:UTASHIRO"

module_maker = "ModuleBuildTiny"
static_install = "auto"

[release]
branch = "main"
hooks = [
    "cd docs; make",
]

[FileGatherer]
exclude_match = [ '^images/.*' ]
