name = "App-Greple-xlate"
badges = [ "github-actions/test.yml" ]
script_files = [ "script/xlate" ]
authority = "cpan:UTASHIRO"

module_maker = "ModuleBuildTiny"
static_install = "auto"

[release]
branch = "main"
hooks = [
    "make -C docs",
    "perl -Ilib -MApp::Greple::xlate=\$VERSION -i -pE 's/^\s*Version \K([\d.]+)/$App::Greple::xlate::VERSION/' script/xlate"
]

[FileGatherer]
exclude_match = [ '^images/.*' ]
