name: Build docker image for texolicom/xlate
on:
  push:
    branches: main
    paths:
      - docker/Dockerfile
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Version and Package
        run: |
          sed 's/^ *//' << END >> $GITHUB_ENV
              PACKAGE=tecolicom/xlate
          END

      # Build Docker Image
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.PACKAGE }}:${GITHUB_REF##*/}
            ${{ env.PACKAGE }}:latest
