name: Build docker image for tecolicom/xlate
on:
  push:
    branches: main
    tags:
      - '*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Version and Package
        run: |
          PACKAGE=tecolicom/xlate
          sed 's/^ *//' << END >> $GITHUB_ENV
              PACKAGE=$PACKAGE
          END
          if [[ "$GITHUB_REF" =~ ^refs/tags/(.+) ]]
          then
              VERSION="${BASH_REMATCH[1]}"
              echo VERSION_TAG="$PACKAGE:$VERSION"
              echo REPO_URL="https://github.com/$GITHUB_REPOSITORY.git@$VERSION"
          else
              echo REPO_URL="https://github.com/$GITHUB_REPOSITORY.git"
          fi >> $GITHUB_ENV

      # Build Docker Image
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: docker
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            REPO_URL=${{ env.REPO_URL }}
          tags: |
            ${{ env.PACKAGE }}:latest
            ${{ env.VERSION_TAG }}
